### ISSUE TITLE
JS Error

### ISSUE THREAD

**Issue by EternalBlack** [Staplegun-US/craft-speedbump#1]
I'm receiving a
```
Uncaught TypeError: Cannot read property 'setAttribute' of null
    at t (speedbump.js:34)
    at HTMLAnchorElement.s (speedbump.js:64)
```
Error inside `speedbump.js` when I click a link (like google.com).

**Comment by kotyy** [comment]
I failed to mention in the readme to add the hook to your _layout.html file.

Adding `{% hook 'speedbump' %}` should solve your issue -- please let me know.

**Comment by kotyy** [comment]
Marking as closed. Let me know if you have other issues.
